Document: pi-cryptenv
Title: Debian pi-cryptenv Manual
Author: <insert document author here>
Abstract: This manual describes what pi-cryptenv is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pi-cryptenv/pi-cryptenv.sgml.gz

Format: postscript
Files: /usr/share/doc/pi-cryptenv/pi-cryptenv.ps.gz

Format: text
Files: /usr/share/doc/pi-cryptenv/pi-cryptenv.text.gz

Format: HTML
Index: /usr/share/doc/pi-cryptenv/html/index.html
Files: /usr/share/doc/pi-cryptenv/html/*.html
